#!/usr/bin/env bash
# Installs Nginx and configures it to serve a Hello World page at its root

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx start
