#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Best School" > /var/www/html/index.nginx-debian.html
echo "This is not a page" > /usr/share/nginx/html/custom_404.html
new_string="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
nstr1="\n\tadd_header X-Served-By \$hostname;"
nstr2="\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$new_string$nstr1$nstr2/" /etc/nginx/sites-enabled/default

sudo service nginx start
